spring:
  thymeleaf:
    enabled: true
    cache: false
    prefix: classpath:templates/

  freemarker:
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity?useUnicode=true&characterEncoding=utf8
    username: testuser
    password: 5678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: none

  security:
    user:
      name: user
      password: 1111

logging:
  level:
    root: info
    com.example.springsecurity: debug

server:
  port: 8283